-- MySQL Script generated by MySQL Workbench
-- Tue Jan 17 22:14:30 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
create database measurements;

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema measurements
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema measurements
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `measurements` DEFAULT CHARACTER SET utf8 ;
USE `measurements` ;

-- -----------------------------------------------------
-- Table `measurements`.`unit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `measurements`.`unit` (
  `id_unit` INT NOT NULL AUTO_INCREMENT,
  `shortname` VARCHAR(5) NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id_unit`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `measurements`.`sensor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `measurements`.`sensor` (
  `id_energymeter` INT NOT NULL AUTO_INCREMENT,
  `id_code` VARCHAR(45) NULL,
  `Description` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`id_energymeter`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `measurements`.`dataset`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `measurements`.`dataset` (
  `id_dataset` INT NOT NULL AUTO_INCREMENT,
  `measurement` DECIMAL(10,5) NOT NULL,
  `date` DATE NOT NULL,
  `timeofday` VARCHAR(45) NULL,
  `unit_id_unit` INT NOT NULL,
  `sensor_id_energymeter` INT NOT NULL,
  PRIMARY KEY (`id_dataset`, `unit_id_unit`),
  INDEX `fk_dataset_unit_idx` (`unit_id_unit` ASC) VISIBLE,
  INDEX `fk_dataset_sensor1_idx` (`sensor_id_energymeter` ASC) VISIBLE,
  CONSTRAINT `fk_dataset_unit`
    FOREIGN KEY (`unit_id_unit`)
    REFERENCES `measurements`.`unit` (`id_unit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dataset_sensor1`
    FOREIGN KEY (`sensor_id_energymeter`)
    REFERENCES `measurements`.`sensor` (`id_energymeter`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
